CONFIG_4TEAM_BUILD = False
CONFIG_USE_TEST_RECIPE = True
CONFIG_SKIP_FW_DOWNLOAD = False
SW_VERSION = "1.0.0"
CONFIG_RECIPE_VERSION = "1.0"
CONFIG_RECIPE_BASE_PATH = "recipes"
#CONFIG_BASE_SHARED_FOLDER_PATH = "\\I40PRDHIASWIN\Collaudi\"

# DB Test config
CONFIG_DB_HOST = "I40TSTHIDBWIN"
CONFIG_DB_USER = "MesReader" 
CONFIG_DB_DATABASE = "HITECO_MDS_SER" 
CONFIG_DB_PSW = "reader" 
# DB Prod config
# CONFIG_DB_HOST = "I40PRDHIDBWIN" 
# CONFIG_DB_USER = "Mes_Reader"  
# CONFIG_DB_DATABASE = "HITECO_MDS"
# CONFIG_DB_PSW = "reader" 

CONFIG_SMB_PORT = 445
CONFIG_SMB_HOST = "\\\\I40PRDHIASWIN\\Collaudi\\"
CONFIG_SMB_USER = "elettromandrini"
# PASSWORD GESTITA DA WINDOWS ?